// anggara-update/src/shared/components/EmptyState.vue
<script setup>
defineProps({
  title: { type: String, default: "Belum ada data" },
  description: { type: String, default: "" },
});
</script>

<template>
  <div
    class="flex flex-col items-center justify-center rounded-lg border border-dashed border-border bg-surface px-6 py-10 text-center"
  >
    <p class="text-sm font-medium text-text">{{ title }}</p>
    <p v-if="description" class="mt-1 max-w-sm text-xs text-text-muted">
      {{ description }}
    </p>
    <slot />
  </div>
</template>

// components/shared/EmptyState.tsx
import type { LucideIcon } from "lucide-react";
import { Inbox } from "lucide-react";
import { cn } from "@/lib/utils";

export function EmptyState({
  icon: Icon = Inbox,
  title,
  description,
  action,
  className,
}: {
  icon?: LucideIcon;
  title: string;
  description?: string;
  action?: React.ReactNode;
  className?: string;
}) {
  return (
    <div
      className={cn(
        "flex flex-col items-center gap-1 rounded-xl border border-dashed px-4 py-10 text-center",
        className,
      )}
    >
      <div className="mb-2 flex size-10 items-center justify-center rounded-full bg-muted text-muted-foreground">
        <Icon className="size-5" />
      </div>
      <p className="text-sm font-medium">{title}</p>
      {description && <p className="max-w-sm text-sm text-muted-foreground">{description}</p>}
      {action && <div className="mt-2">{action}</div>}
    </div>
  );
}
