// anggara-update/src/features/proposals/components/ProposalDetail.vue
<script setup>
import { computed } from "vue";
import { useRoute, useRouter } from "vue-router";
import { ArrowLeft } from "lucide-vue-next";
import { Badge } from "@/shared/components/ui/badge";
import { Button } from "@/shared/components/ui/button";
import Skeleton from "@/shared/components/Skeleton.vue";
import EmptyState from "@/shared/components/EmptyState.vue";
import ErrorState from "@/shared/components/ErrorState.vue";
import { formatRupiah, formatDate } from "@/shared/lib/format";
import { proposalStatusLabel, proposalStatusVariant } from "@/shared/lib/status";
import { useProposal } from "@/features/proposals/composables/useProposals";
import ReviewActions from "@/features/proposals/components/ReviewActions.vue";

const route = useRoute();
const router = useRouter();
const id = computed(() => route.params.id);

const { data, isLoading, isError, error, refetch } = useProposal(id);
const p = computed(() => data.value);

const anggaran = computed(() => p.value?.anggaran?.[0] || null);
const revisions = computed(() => p.value?.proposal_revisions || []);
</script>

<template>
  <div class="space-y-6">
    <Button variant="ghost" size="sm" class="gap-1" @click="router.back()">
      <ArrowLeft class="size-4" /> Kembali
    </Button>

    <ErrorState
      v-if="isError"
      :message="error?.message || 'Gagal memuat proposal.'"
      @retry="refetch()"
    />

    <Skeleton v-else-if="isLoading" class="h-96 w-full rounded-lg" />

    <EmptyState
      v-else-if="!p"
      title="Proposal tidak ditemukan"
      description="Proposal mungkin telah dihapus atau Anda tidak memiliki akses."
    />

    <template v-else>
      <header class="space-y-2">
        <div class="flex flex-wrap items-center gap-3">
          <h1 class="text-xl font-bold text-text">{{ p.judul_kegiatan }}</h1>
          <Badge :variant="proposalStatusVariant[p.status]">{{
            proposalStatusLabel[p.status]
          }}</Badge>
        </div>
        <p class="text-sm text-text-muted">
          {{ p.ormawa?.nama || "-" }}
          <span v-if="p.ormawa?.jenis"> · {{ p.ormawa.jenis }}</span>
        </p>
        <ReviewActions :proposal="p" />
      </header>

      <div class="grid grid-cols-1 gap-4 lg:grid-cols-3">
        <!-- Main info -->
        <section class="space-y-4 lg:col-span-2">
          <div class="rounded-lg border border-border bg-surface p-4 shadow-sm">
            <h2 class="mb-3 text-sm font-semibold text-text">Informasi Kegiatan</h2>
            <dl class="grid grid-cols-1 gap-x-6 gap-y-3 text-sm sm:grid-cols-2">
              <div>
                <dt class="text-text-muted">Anggaran Diajukan</dt>
                <dd class="font-medium text-text">
                  {{ formatRupiah(p.anggaran_diajukan) }}
                </dd>
              </div>
              <div>
                <dt class="text-text-muted">Lokasi</dt>
                <dd class="font-medium text-text">{{ p.lokasi || "-" }}</dd>
              </div>
              <div>
                <dt class="text-text-muted">Tanggal Mulai</dt>
                <dd class="font-medium text-text">
                  {{ formatDate(p.tanggal_mulai) }}
                </dd>
              </div>
              <div>
                <dt class="text-text-muted">Tanggal Selesai</dt>
                <dd class="font-medium text-text">
                  {{ formatDate(p.tanggal_selesai) }}
                </dd>
              </div>
            </dl>
          </div>

          <div class="rounded-lg border border-border bg-surface p-4 shadow-sm">
            <h2 class="mb-2 text-sm font-semibold text-text">Deskripsi</h2>
            <p class="whitespace-pre-line text-sm text-text">
              {{ p.deskripsi || "-" }}
            </p>
          </div>

          <div class="rounded-lg border border-border bg-surface p-4 shadow-sm">
            <h2 class="mb-2 text-sm font-semibold text-text">Tujuan Kegiatan</h2>
            <p class="whitespace-pre-line text-sm text-text">
              {{ p.tujuan_kegiatan || "-" }}
            </p>
          </div>
        </section>

        <!-- Side: anggaran + revisions -->
        <aside class="space-y-4">
          <div class="rounded-lg border border-border bg-surface p-4 shadow-sm">
            <h2 class="mb-3 text-sm font-semibold text-text">Anggaran</h2>
            <template v-if="anggaran">
              <dl class="space-y-2 text-sm">
                <div class="flex justify-between">
                  <dt class="text-text-muted">Disetujui</dt>
                  <dd class="font-medium text-text">
                    {{ formatRupiah(anggaran.nominal_disetujui) }}
                  </dd>
                </div>
                <div class="flex justify-between">
                  <dt class="text-text-muted">Ditetapkan</dt>
                  <dd class="font-medium text-text">
                    {{ formatDate(anggaran.ditetapkan_pada) }}
                  </dd>
                </div>
              </dl>
              <p v-if="anggaran.catatan_anggaran" class="mt-3 text-xs text-text-muted">
                {{ anggaran.catatan_anggaran }}
              </p>
            </template>
            <p v-else class="text-sm text-text-muted">Belum ditetapkan.</p>
          </div>

          <div class="rounded-lg border border-border bg-surface p-4 shadow-sm">
            <h2 class="mb-3 text-sm font-semibold text-text">Riwayat Revisi</h2>
            <ul v-if="revisions.length" class="space-y-3 text-sm">
              <li
                v-for="r in revisions"
                :key="r.id"
                class="border-b border-border pb-2 last:border-0 last:pb-0"
              >
                <p class="font-medium text-text">Versi {{ r.versi }}</p>
                <p class="text-text-muted">{{ r.catatan || "-" }}</p>
                <p class="mt-1 text-xs text-text-muted">
                  {{ formatDate(r.created_at) }}
                </p>
              </li>
            </ul>
            <p v-else class="text-sm text-text-muted">Belum ada revisi.</p>
          </div>
        </aside>
      </div>
    </template>
  </div>
</template>

// components/proposal/ProposalDetail.tsx
import { RUPIAH, TANGGAL } from "@/lib/constants";
import type { StatusProposal } from "@/lib/db/schema";
import { StatusBadge } from "@/components/shared/StatusBadge";
import { ReviewActions } from "@/components/proposal/ReviewActions";
import { PdfPreviewDialog } from "@/components/shared/PdfPreviewDialog";

type ProposalDetailData = NonNullable<Awaited<ReturnType<typeof import("@/lib/db/queries/lkpka").getProposalForReview>>>;

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="flex flex-col gap-1 border-t py-4 first:border-t-0 first:pt-0 sm:grid sm:grid-cols-[200px_1fr] sm:gap-4">
      <dt className="text-sm font-medium text-muted-foreground">{label}</dt>
      <dd className="text-sm leading-relaxed">{children}</dd>
    </div>
  );
}

export function ProposalDetail({
  proposal,
  readOnly = false,
}: {
  proposal: ProposalDetailData;
  readOnly?: boolean;
}) {
  return (
    <div className="flex flex-col gap-6">
      <div className="flex flex-col gap-3">
        <div className="flex flex-wrap items-center gap-3">
          <StatusBadge status={proposal.status as StatusProposal} />
          <span className="text-xs text-muted-foreground">
            Versi {proposal.versi_revisi + 1} · Diajukan {TANGGAL.format(new Date(proposal.created_at))}
          </span>
        </div>
        <h1 className="text-2xl font-bold tracking-tight">{proposal.judul_kegiatan}</h1>
        <p className="text-sm text-muted-foreground">
          {proposal.ormawaNama} · {proposal.ormawaJenis}
        </p>
        {proposal.catatan_review && (
          <div className="rounded-lg border bg-muted/40 px-4 py-3">
            <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
              Catatan review
            </p>
            <p className="mt-1 text-sm">{proposal.catatan_review}</p>
          </div>
        )}
      </div>

      <dl>
        <Field label="Deskripsi kegiatan">{proposal.deskripsi}</Field>
        <Field label="Tujuan kegiatan">{proposal.tujuan_kegiatan}</Field>
        <Field label="Pelaksanaan">
          {TANGGAL.format(new Date(proposal.tanggal_mulai))} — {TANGGAL.format(new Date(proposal.tanggal_selesai))}
        </Field>
        <Field label="Lokasi">{proposal.lokasi}</Field>
        <Field label="Anggaran diajukan">{RUPIAH.format(Number(proposal.anggaran_diajukan))}</Field>
        <Field label="PDF proposal">
          {proposal.file_proposal_url ? (
            <PdfPreviewDialog url={proposal.file_proposal_url} label="Buka PDF proposal" />
          ) : (
            <span className="text-muted-foreground">PDF belum diunggah</span>
          )}
        </Field>
        {proposal.anggaran && (
          <>
            <Field label="Anggaran disetujui">
              <span className="font-semibold text-emerald-700">
                {RUPIAH.format(Number(proposal.anggaran.nominal_disetujui))}
              </span>
            </Field>
            <Field label="Catatan anggaran">
              {proposal.anggaran.catatan_anggaran ?? "—"}
            </Field>
            <Field label="Ditetapkan pada">
              {TANGGAL.format(new Date(proposal.anggaran.ditetapkan_pada))}
            </Field>
          </>
        )}
      </dl>

      {!readOnly && proposal.status === "diajukan" && (
        <div className="border-t pt-6">
          <p className="mb-3 text-sm font-medium">Putusan review</p>
          <ReviewActions proposalId={proposal.id} anggaranDiajukan={proposal.anggaran_diajukan} />
        </div>
      )}

      {proposal.revisions.length > 0 && (
        <div className="border-t pt-6">
          <p className="mb-3 text-sm font-medium">Riwayat revisi</p>
          <ol className="flex flex-col gap-4">
            {proposal.revisions.map((r) => (
              <li key={r.versi} className="flex gap-4">
                <div className="flex flex-col items-center">
                  <span className="flex size-8 shrink-0 items-center justify-center rounded-full border bg-muted text-xs font-semibold">
                    v{r.versi}
                  </span>
                  <span className="mt-1 h-full w-px bg-border" aria-hidden />
                </div>
                <div className="pb-2">
                  <p className="text-xs text-muted-foreground">
                    {TANGGAL.format(new Date(r.created_at))}
                  </p>
                  <p className="mt-0.5 text-sm">{r.catatan ?? "Revisi tanpa catatan"}</p>
                </div>
              </li>
            ))}
          </ol>
        </div>
      )}
    </div>
  );
}
